spring:
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:mysql:8.0.34:///test
    username: test
    password: test

redis:
  host: redis
  port: 6379
