spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(lQic2Jn3tefh1UoISQEIZu1zNjZQ4AgO0CdpR6MIEIsUMjAeaZZEbTpRRzK4MOD908OIwpuJ0LjanKkQv6fek8ANeICef0oyC/YeBlB1/8gAPe8zKnAE9ybxnEknnNLu)
    username: ENC(eWUVBZoiFvNSRMNW00LEbg==)
    password: ENC(QHs+cR+IbpsNUx+QO6mgj3p5bibv1BXi)
